title: "CSS by examples"
baseurl: ""
url: "https://css-by-examples.com"

social_links:
  github: "css-by-examples"

# Build settings
markdown: kramdown

autoprefixer:
  browsers:
    - last 7 versions
    - not ie <= 10
    - not ie_mob <= 10

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-autoprefixer
  - jekyll-seo-tag

collections:
  examples:
    output: true